=== nikhilratakonda/assignment3-part3/courses.dtd
<!ELEMENT courses (course+)>
<!ELEMENT course (course_id, name, major, credits)>
<!ELEMENT course_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT credits (#PCDATA)>
<!ATTLIST courses xmlns:xsi CDATA #IMPLIED>

=== nikhilratakonda/assignment3-part3/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE courses SYSTEM "courses.dtd">
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<course>
		<course_id>CS608</course_id>
		<name>Algorithms and computational theory</name>
		<major>Computer Science</major>
		<credits>3</credits>
	</course>
	<course>
		<course_id>CS613</course_id>
		<name>Internet computing</name>
		<major>Computer Science</major>
		<credits>3</credits>
	</course>
		<course>
		<course_id>CS612</course_id>
		<name>introduction to Parallel computing</name>
		<major>Computer Science</major>
		<credits>3</credits>
	</course>
</courses>
